name: clone submodules

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
            
permissions: write-all

jobs:
  clone-submodules:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
        with:
          repository: MichaelGrafnetter/DSInternals
          path: DSInternals
      - uses: actions/checkout@v2
      - run: |
          git submodule add https://github.com/MichaelGrafnetter/DSInternals.git DSInternals
        continue-on-error: true 
       
      - uses: actions/checkout@v2
        with:
          repository: sqlmapproject/sqlmap
          path: sqlmap
      - uses: actions/checkout@v2
      - run: | 
          git config user.name liranpi2
          git submodule add https://github.com/sqlmapproject/sqlmap.git sqlmap
        continue-on-error: true 
        
      - uses: actions/checkout@v2
        with:
          repository: SnaffCon/Snaffler
          path: Snaffler
      - uses: actions/checkout@v2
      - run: | 
          DIR="./Snaffler"
          if [ -d "$DIR" ]; then
            git submodule add https://github.com/SnaffCon/Snaffler.git
            echo "Installing config files in ${DIR}..."
          fi
         continue-on-error: true 
         
      - uses: actions/checkout@v2
      - run: | 
          git config user.name liranpi2
          git pull --recurse-submodules
          git add .
          git commit -m "add submodule"
          git push
        continue-on-error: true
